/*
 * Kenjo API
 * Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AreasCreateNewAreaRequest;
import com.konfigthis.client.model.AreasCreateNewAreaResponse;
import com.konfigthis.client.model.AreasGetByIdResponse;
import com.konfigthis.client.model.AreasGetListResponseInner;
import com.konfigthis.client.model.AreasUpdateAreaByIdRequest;
import com.konfigthis.client.model.AreasUpdateAreaByIdResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AreasApi
 */
@Disabled
public class AreasApiTest {

    private static AreasApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AreasApi(apiClient);
    }

    /**
     * Creates a new area.&lt;br&gt;The *name* is the only required field.&lt;br&gt;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewAreaTest() throws ApiException {
        String authorization = null;
        String name = null;
        AreasCreateNewAreaResponse response = api.createNewArea(authorization)
                .name(name)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns the area referenced by *id*.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        String authorization = null;
        AreasGetByIdResponse response = api.getById(id, authorization)
                .execute();
        // TODO: test validations
    }

    /**
     * Returns a list of the existing areas in Kenjo.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListTest() throws ApiException {
        String authorization = null;
        List<AreasGetListResponseInner> response = api.getList(authorization)
                .execute();
        // TODO: test validations
    }

    /**
     * Removes the area referenced by *id*.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void removeByIdTest() throws ApiException {
        String id = null;
        String authorization = null;
        api.removeById(id, authorization)
                .execute();
        // TODO: test validations
    }

    /**
     * Updates a area referenced by *id*. Only the attributes submitted are modified.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateAreaByIdTest() throws ApiException {
        String id = null;
        String authorization = null;
        String name = null;
        AreasUpdateAreaByIdResponse response = api.updateAreaById(id, authorization)
                .name(name)
                .execute();
        // TODO: test validations
    }

}
