/*
 * Kenjo API
 * Before starting to use the Kenjo API, you have to request the API activation for a sandbox or production environment to the Kenjo Customer Success team. After that, an admin user has to go to *Settings > Integrations > API keys*, to generate the **API Key**. Follow the steps described in the **Autentication section** of this document. <br>The API key is needed to request the bearer token. Each endpoint callout requires a valid bearer token in the Authorization header. Once the token is retrieved, it will be useful during the time limit indicated by the 'expiration date'.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.AuthenticationCreateBearerTokenRequest;
import com.konfigthis.client.model.AuthenticationCreateBearerTokenResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticationApi
 */
@Disabled
public class AuthenticationApiTest {

    private static AuthenticationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new AuthenticationApi(apiClient);
    }

    /**
     * Create a bearer token to allow connecting the API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBearerTokenTest() throws ApiException {
        String apiKey = null;
        AuthenticationCreateBearerTokenResponse response = api.createBearerToken()
                .apiKey(apiKey)
                .execute();
        // TODO: test validations
    }

    /**
     * Invalidates a Bearer token.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void invalidateTokenTest() throws ApiException {
        api.invalidateToken()
                .execute();
        // TODO: test validations
    }

}
